-- Desde SYSTEM

-- Creamos los usuarios para cada rol

-- 1. Conectarse al contenedor correcto
ALTER SESSION SET CONTAINER = XEPDB1;

-- 2. Crear usuario GESTOR
CREATE USER USUARIO_GESTOR IDENTIFIED BY Gestor123
DEFAULT TABLESPACE USERS
QUOTA 20M ON USERS;
GRANT CREATE SESSION TO USUARIO_GESTOR;

-- 3. Crear usuario RECOLECCION
CREATE USER USUARIO_RECOLECCION IDENTIFIED BY Recoleccion123
DEFAULT TABLESPACE USERS
QUOTA 20M ON USERS;
GRANT CREATE SESSION TO USUARIO_RECOLECCION;

-- 4. Crear usuario ANALISTA
CREATE USER USUARIO_ANALISTA IDENTIFIED BY Analista123
DEFAULT TABLESPACE USERS
QUOTA 20M ON USERS;
GRANT CREATE SESSION TO USUARIO_ANALISTA;

COMMIT;
