--Desde SYSTEM

-- Asignacion de roles a usuarios correspondientes

-- 1. Asignar ROL_GESTOR a USUARIO_GESTOR
GRANT ROL_GESTOR TO USUARIO_GESTOR;

-- 2. Asignar ROL_RECOLECCION a USUARIO_RECOLECCION
GRANT ROL_RECOLECCION TO USUARIO_RECOLECCION;

-- 3. Asignar ROL_ANALISTA a USUARIO_ANALISTA
GRANT ROL_ANALISTA TO USUARIO_ANALISTA;

COMMIT;